import fs from 'node:fs/promises';
import { FileBlob, PresentationFile } from '@oai/artifact-tool';

const TMP = 'C:/Users/Gajula Sathish/AppData/Local/Temp/codex-presentations/manual-20260807/credence-case-study/tmp';
const STARTER = `${TMP}/template-starter.pptx`;
const OUTPUT = 'C:/Project/Frontend/outputs/Credence_Credit_Card_Management_Case_Study_2026.pptx';
const PREVIEW = `${TMP}/preview/final`;
const LAYOUT = `${TMP}/layout/final`;
const FOOTER = 'Copyright © 2026, Oracle and/or its affiliates  |  Confidential: Internal/Restricted/Highly Restricted';

const titles = [
  '',
  'Why Credence was needed',
  'The project turns requirements into measurable controls',
  'Live APIs keep every role on one source of truth',
  'Each service owns one business capability',
  'JWT and role boundaries protect every experience',
  'A card account is more than a physical card',
  'Credit is reserved before settlement—not after',
  'Validation is enforced where the business rule lives',
  'The dashboard turns live activity into action',
  'Card operations stay searchable, governed and auditable',
  'Customer details connect identity, cards and alerts',
  'Merchant details expose eligible cards and transaction history',
  'Card details bring status, balance and lifecycle controls together',
  'A complete transaction record supports investigation',
  'The AI assistant adds governed natural-language operations',
  'The hardest issues became reusable engineering safeguards',
  '',
];

const bodyCopy = {
  2: [
    '• Credit-card operations were split across customers, cards, merchants, transactions and due-date tracking.',
    '• Hard-coded UI records could not guarantee that edits, balances, statuses and alerts stayed synchronized.',
    '• Pending debits created a risk: several transactions could later settle beyond the true account limit.',
    '• Primary and add-on cards needed one shared balance, tier, billing date and renewal history.',
    '• Managers and customers required different permissions without duplicating the application.',
    '• The solution had to remain traceable: live APIs, persisted entities, protected routes and auditable history.',
  ].join('\n'),
  3: [
    '• Replace hard-coded records with real-time CRUD operations across every entity.',
    '• Provide secure manager and customer journeys with JWT login, refresh and protected deep links.',
    '• Enforce card eligibility, merchant status, shared limits, repayments, due dates and renewals consistently.',
    '• Make operational data understandable through search, filters, pagination, alerts and smooth trend charts.',
    '• Keep destructive and financial actions explicit through concise validation and confirmation dialogs.',
    '• Add an AI assistant that can read live data and propose governed backend actions for confirmation.',
  ].join('\n'),
  5: [
    '• Manager / Auth — account registration, BCrypt credentials, JWT issuance and refresh; port 8085.',
    '• Customer — identity, profile validation, credentials and coordinated deletion; port 8081.',
    '• Credit Cards — issue, status, shared balances, recurring dates, renewal and replacement links; port 8082.',
    '• Transactions — purchases, authorizations, repayments, holds, settlement and deletion; port 8083.',
    '• Merchant — merchant profile, unique identifiers, status and transaction eligibility; port 8084.',
    '• Angular 22 consumes live endpoints; Oracle persists each service model; Eureka supports discovery.',
  ].join('\n'),
  6: [
    '• Manager: creates customers, allocates credentials, issues cards, manages merchants and settles operations.',
    '• Customer: signs in only after manager provisioning and sees only their account, cards and transactions.',
    '• Customer may request a card, block immediately, renew when eligible and transact with active merchants.',
    '• Route guards preserve the requested return URL and reject protected navigation without a valid token.',
    '• A refresh timer renews the JWT before expiry; failed refresh clears the session and returns to login.',
    '• Bearer tokens accompany every protected API request; passwords are stored only as BCrypt hashes.',
  ].join('\n'),
  7: [
    '• One customer has at most two current cards: one PRIMARY and one ADD_ON.',
    '• The pair shares tier, limit, available credit, due date and expiry date.',
    '• Card numbers are unique 12-digit values generated by the service—not typed by users.',
    '• INACTIVE, BLOCKED, expired or replaced cards cannot transact or be reactivated.',
    '• Renewal creates successor physical cards, preserves account context and inactivates predecessors.',
    '• Historic cards remain linked for audit, but alerts, repayments and balances target current replacements.',
  ].join('\n'),
  9: [
    '• Customer: unique 12-digit Aadhaar/account, unique 10-digit mobile and non-null creation timestamp.',
    '• Card: unique generated number, one card per type, maximum two current cards and due date before expiry.',
    '• Merchant: unique MID/account number; only ACTIVE merchants are eligible for new transactions.',
    '• Transaction: positive amount, valid status transition, eligible card and sufficient effective credit.',
    '• Repayment: cannot exceed outstanding debt and is refused when available credit already equals the limit.',
    '• Lists: live search, combined filters, concise dialog errors and pagination in pages of ten.',
  ].join('\n'),
  16: [
    '• Streaming chat preserves prior conversations and names them from the user’s intent.',
    '• Tool calling maps natural language to backend operations that use the same entity schemas and rules.',
    '• Read tools answer questions from live customer, card, merchant and transaction data—only what was asked.',
    '• Write tools show a structured confirmation card before execution; success replaces the pending prompt.',
    '• Generated identifiers stay server-owned; reference values are resolved to the required entity IDs.',
    '• Scope guardrails keep the assistant focused on Credence operations instead of general-purpose requests.',
  ].join('\n'),
  17: [
    '• Shared-balance drift → one account-level balance plus reservation/release semantics across both cards.',
    '• Renewal confusion → replacement links, historic-card exclusion and current-card alert targeting.',
    '• UTC/local mismatch → UTC persistence with explicit Asia/Kolkata presentation formatting.',
    '• Raw stack traces → centralized concise API messages rendered inside the active dialog.',
    '• UI migration complexity → feature components, shared shell/modal/card/pagination and route parity.',
    '• Verification → Angular development build plus service compilation and acceptance scenarios for auth, limits, status, renewal, repayment and deletion.',
    '',
    'Takeaway: financial correctness comes from domain invariants and coordinated service workflows—not from UI validation alone.',
  ].join('\n'),
};

const screenshots = {
  10: `${TMP}/assets/needs-attention.png`,
  11: `${TMP}/assets/cards.png`,
  12: `${TMP}/assets/customer-details.png`,
  13: `${TMP}/assets/merchant-details.png`,
  14: `${TMP}/assets/card-details.png`,
  15: `${TMP}/assets/transaction-details.png`,
};

async function imageBytes(path) {
  const bytes = await fs.readFile(path);
  return bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);
}

function shapeByName(slide, name) {
  const shape = slide.shapes.getItem(name);
  if (!shape) throw new Error(`Missing shape ${name}`);
  return shape;
}

function setTitle(slide, text) {
  const title = shapeByName(slide, 'Title 13');
  title.position = { left: 88, top: 42, width: 1104, height: 112 };
  title.text = text;
  title.text.style = { fontSize: 46, color: '#312D2A' };
}

function svgBytes(svg) {
  const bytes = new TextEncoder().encode(svg);
  return bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);
}

function cleanText(text) {
  return text
    .replaceAll('â€¢', '•')
    .replaceAll('â€”', '—')
    .replaceAll('â†’', '→')
    .replaceAll('â€™', '’')
    .replaceAll('Â©', '©');
}

function xmlEscape(text) {
  return cleanText(text)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function wrapWords(text, limit = 96) {
  const words = text.trim().split(/\s+/);
  const lines = [];
  let line = '';
  for (const word of words) {
    const next = line ? `${line} ${word}` : word;
    if (next.length > limit && line) {
      lines.push(line);
      line = word;
    } else {
      line = next;
    }
  }
  if (line) lines.push(line);
  return lines;
}

async function setBody(slide, text, slideNumber) {
  shapeByName(slide, 'Content Placeholder 15').delete();
  slide.images.add({
    blob: await imageBytes(`${TMP}/assets/body-${slideNumber}.png`),
    contentType: 'image/png',
    alt: `Credence case study details for slide ${slideNumber}`,
    fit: 'contain',
    position: { left: 104, top: 174, width: 1064, height: 440 },
  });
}
function setChrome(slide, number) {
  const decorativePicture = slide.shapes.getItem('Picture 8');
  if (decorativePicture) decorativePicture.delete();
  const decorativeMarker = slide.shapes.getItem('Rectangle 2');
  if (decorativeMarker) decorativeMarker.delete();
  const footer = shapeByName(slide, 'Footer Placeholder 5');
  footer.text = FOOTER;
  footer.text.style = { fontSize: 16, color: '#312D2A' };
  const page = shapeByName(slide, 'Slide Number Placeholder 4');
  page.text = String(number);
  page.text.style = { fontSize: 16, color: '#312D2A', alignment: 'right' };
}

function addNode(slide, name, text, x, y, w, h, fill = '#F7F4F2', line = '#C74634') {
  const node = slide.shapes.add({
    geometry: 'roundRect',
    name,
    position: { left: x, top: y, width: w, height: h },
    fill: { type: 'solid', color: fill },
    line: { style: 'solid', fill: line, width: 2 },
    borderRadius: 'rounded-lg',
  });
  node.text = text;
  node.text.style = { fontSize: 18, bold: true, color: '#312D2A', alignment: 'center', verticalAlignment: 'middle' };
  return node;
}

function architectureDiagram(slide) {
  shapeByName(slide, 'Content Placeholder 15').delete();
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1112" height="470" viewBox="0 0 1112 470">
    <rect width="1112" height="470" fill="#FFFFFF"/>
    <g stroke="#C74634" stroke-width="2" fill="none">
      <line x1="556" y1="82" x2="125" y2="198"/><line x1="556" y1="82" x2="340" y2="198"/><line x1="556" y1="82" x2="556" y2="198"/><line x1="556" y1="82" x2="772" y2="198"/><line x1="556" y1="82" x2="987" y2="198"/>
    </g>
    <g stroke="#5F5CCB" stroke-width="2" fill="none">
      <line x1="125" y1="276" x2="556" y2="360"/><line x1="340" y1="276" x2="556" y2="360"/><line x1="556" y1="276" x2="556" y2="360"/><line x1="772" y1="276" x2="556" y2="360"/><line x1="987" y1="276" x2="556" y2="360"/>
    </g>
    <rect x="406" y="18" width="300" height="64" rx="12" fill="#FFF3E8" stroke="#C74634" stroke-width="2"/>
    <text x="556" y="43" text-anchor="middle" font-family="Calibri,Arial" font-weight="700" font-size="20" fill="#312D2A">Angular 22 UI</text><text x="556" y="66" text-anchor="middle" font-family="Calibri,Arial" font-size="17" fill="#312D2A">Manager + Customer portals</text>
    ${[['Manager / Auth','8085',30],['Customer','8081',245],['Credit Cards','8082',461],['Transactions','8083',677],['Merchant','8084',892]].map(([a,b,x])=>`<rect x="${x}" y="198" width="190" height="78" rx="10" fill="#FFFFFF" stroke="#9C8C84" stroke-width="2"/><text x="${Number(x)+95}" y="229" text-anchor="middle" font-family="Calibri,Arial" font-weight="700" font-size="18" fill="#312D2A">${a}</text><text x="${Number(x)+95}" y="254" text-anchor="middle" font-family="Calibri,Arial" font-size="16" fill="#312D2A">${b}</text>`).join('')}
    <rect x="406" y="360" width="300" height="70" rx="12" fill="#F2F0FF" stroke="#5F5CCB" stroke-width="2"/><text x="556" y="390" text-anchor="middle" font-family="Calibri,Arial" font-weight="700" font-size="20" fill="#312D2A">Oracle Database</text><text x="556" y="415" text-anchor="middle" font-family="Calibri,Arial" font-size="17" fill="#312D2A">JPA repositories</text>
  </svg>`;
  slide.images.add({ blob: svgBytes(svg), contentType: 'image/svg+xml', alt: 'Credence microservice architecture', fit: 'contain', position: { left: 84, top: 164, width: 1112, height: 470 } });
}
async function transactionFlow(slide) {
  shapeByName(slide, 'Content Placeholder 15').delete();
  slide.images.add({
    blob: await imageBytes(`${TMP}/assets/flow.png`),
    contentType: 'image/png',
    alt: 'Transaction reservation and settlement process',
    fit: 'contain',
    position: { left: 84, top: 164, width: 1112, height: 470 },
  });
}
async function replaceBodyWithScreenshot(slide, path, alt) {
  shapeByName(slide, 'Content Placeholder 15').delete();
  slide.images.add({
    blob: await imageBytes(path),
    contentType: 'image/png',
    alt,
    fit: 'contain',
    position: { left: 84, top: 164, width: 1112, height: 470 },
  });
}

async function saveBlob(path, blob) {
  await fs.mkdir(path.substring(0, path.lastIndexOf('/')), { recursive: true });
  await fs.writeFile(path, new Uint8Array(await blob.arrayBuffer()));
}

const presentation = await PresentationFile.importPptx(await FileBlob.load(STARTER));

const cover = presentation.slides.getItem(0);
shapeByName(cover, 'Text Placeholder 11').delete();
const coverTitle = shapeByName(cover, 'Title 13');
coverTitle.text = 'Credence — Credit Card Management System';
const coverMeta = shapeByName(cover, 'Text Placeholder 12');
coverMeta.text = 'Gajula Sathish\n07 August 2026\nGrad-hire Project | Angular + Spring Boot Microservices';

for (let n = 2; n <= 17; n += 1) {
  const slide = presentation.slides.getItem(n - 1);
  setTitle(slide, titles[n]);
  setChrome(slide, n);
  if (bodyCopy[n]) await setBody(slide, bodyCopy[n], n);
}

architectureDiagram(presentation.slides.getItem(3));
await transactionFlow(presentation.slides.getItem(7));

for (const [slideNumber, path] of Object.entries(screenshots)) {
  await replaceBodyWithScreenshot(
    presentation.slides.getItem(Number(slideNumber) - 1),
    path,
    `${titles[slideNumber]} — Credence Angular application screenshot`,
  );
}

const closing = presentation.slides.getItem(17);
shapeByName(closing, 'Text Placeholder 1').delete();
shapeByName(closing, 'Title 2').delete();
shapeByName(closing, 'Text Placeholder 5').delete();
shapeByName(closing, 'Footer Placeholder 3').text = FOOTER;
shapeByName(closing, 'Slide Number Placeholder 4').text = '18';
const closingText = shapeByName(closing, 'TextBox 11');
closingText.text = '\n\n\n\nCredence demonstrates how secure domain rules, live microservices and a role-aware Angular experience can manage the complete credit-card lifecycle.\n\nQuestions & comments';
closingText.text.style = { fontSize: 27, color: '#312D2A' };

await fs.mkdir(PREVIEW, { recursive: true });
await fs.mkdir(LAYOUT, { recursive: true });
await fs.mkdir('C:/Project/Frontend/outputs', { recursive: true });

for (let i = 0; i < presentation.slides.items.length; i += 1) {
  const slide = presentation.slides.getItem(i);
  const stem = `slide-${String(i + 1).padStart(2, '0')}`;
  try {
    await saveBlob(`${PREVIEW}/${stem}.png`, await presentation.export({ slide, format: 'png', scale: 1 }));
  } catch (error) {
    console.warn(`Preview warning for ${stem}: ${error.message}`);
  }
  const layout = await slide.export({ format: 'layout' });
  await fs.writeFile(`${LAYOUT}/${stem}.layout.json`, await layout.text());
}

const pptx = await PresentationFile.exportPptx(presentation);
await pptx.save(OUTPUT);
console.log(OUTPUT);
